services:
  app:
    build: ./app
    container_name: app
    links:
      - db
    ports:
      - 5001:5000
  db:
    image: mysql:latest
    container_name: mileage_db
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: your_database
    volumes:
      - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - 3306:3306